showerthoughts/Models/thought.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace showerthoughts.Models
{
    public class thought
    {
        public int id { get; set; }
        public string title { get; set; }   
 
        [AllowHtml]
        public string bdText { get; set; }

        public DateTime date { get; set; }
        public int rate { get; set; }
        
        //autor

        public string authorId { get; set; } 

        //subthought
    }
}

showerthoughts/Controllers/ThoughtController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using showerthoughts.Models;

namespace showerthoughts.Controllers
{
    public class ThoughtController : Controller
    {
        showerthoughtsDBContext db = new showerthoughtsDBContext();

        // GET: Thought
        public ActionResult Index()
        {
            return View(db.thoughts.ToList());
        }

        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]        
        public ActionResult Create(thought thought)
        {
            thought.rate = 0;

            thought.authorId = User.Identity.Name;
            thought.date = DateTime.Now;

            if (ModelState.IsValid)
            {
                db.thoughts.Add(thought);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public ActionResult goToThought(int id)
        {
            thought thought = db.thoughts.Find(id);
            return View(thought);
        }

    }
}

showerthoughts/Views/Thought/Create.cshtml
@model showerthoughts.Models.thought

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<script src="~/Scripts/ckeditor/ckeditor.js"></script>

@using (Html.BeginForm("Create", "Thought", FormMethod.Post, new { id="myForm" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>thought</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.bdText, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.bdText, new { htmlAttributes = new { @class = "form-control ckeditor", @id = "editor1" } })
                @Html.ValidationMessageFor(model => model.bdText, "", new { @class = "text-danger" })
            </div>
        </div> 
        @*<div class="form-group">
            @Html.LabelFor(model => model.date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
            </div>
        </div>*@        
  
        <script>
           CKEDITOR.replace('editor1');            
        </script>           
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
<script src="~/Scripts/jquery-3.1.1.min.js"></script>
<script src="~/Scripts/mycustom.js"></script>

showerthoughts/Views/Thought/Index.cshtml
@using System.Web
@model IEnumerable<showerthoughts.Models.thought>

@foreach (var item in Model)
{

    <div>

        <div> @Html.ActionLink(item.title, "goToThought", new { id = item.id }) </div>

        <div>@Html.Raw(item.bdText) </div>

        @Html.DisplayFor(modelItem => item.date)
        <p>
            @Html.DisplayFor(modelItem => item.rate)
        </p>
        <p>
            @Html.DisplayFor(modelItem => item.authorId)
        </p>
    </div>
}

showerthoughts/Views/Thought/goToThought.cshtml
@model showerthoughts.Models.thought


<div>
    <h4>thought</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.bdText)
        </dt>

        <dd>
            @Html.Raw(Model.bdText)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.rate)
        </dd>

    </dl>
</div>